# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: finance.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'finance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rfinance.proto\x12\x07\x66inance\"\x89\x01\n\x14RecordPaymentRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x10\n\x08order_id\x18\x02 \x01(\t\x12\x12\n\npayment_id\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x16\n\x0epayment_method\x18\x06 \x01(\t\"Q\n\x15RecordPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65ntry_id\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t2f\n\x0e\x46inanceService\x12T\n\x13RecordLedgerPayment\x12\x1d.finance.RecordPaymentRequest\x1a\x1e.finance.RecordPaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'finance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECORDPAYMENTREQUEST']._serialized_start=27
  _globals['_RECORDPAYMENTREQUEST']._serialized_end=164
  _globals['_RECORDPAYMENTRESPONSE']._serialized_start=166
  _globals['_RECORDPAYMENTRESPONSE']._serialized_end=247
  _globals['_FINANCESERVICE']._serialized_start=249
  _globals['_FINANCESERVICE']._serialized_end=351
# @@protoc_insertion_point(module_scope)
