# Generated by Django 4.2.30 on 2026-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraddress_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER', 'Order Update'), ('PAYMENT', 'Payment Status'), ('SYSTEM', 'System Alert'), ('PROMO', 'Promotion'), ('SHIPMENT', 'Shipment Status'), ('ITEM_REQUEST', 'Product Request'), ('CHAT', 'Chat Message')], default='SYSTEM', max_length=20),
        ),
    ]
