# Generated by Django 4.2.30 on 2026-09-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_role_user_authenticat_role_7fb088_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='authenticat_user_id_2f156f_idx',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='Before and after state values'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['tenant_id', '-timestamp'], name='authenticat_tenant__7b1acc_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['actor_id', '-timestamp'], name='authenticat_actor_i_5d7c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='authenticat_resourc_f70c54_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-timestamp'], name='authenticat_action_1dbc94_idx'),
        ),
    ]
