# Generated by Django 4.2.30 on 2026-09-12 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_activitylog_authenticat_user_id_2f156f_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SHOP_OWNER', 'Shop Owner'), ('SHOP_ADMIN', 'Shop Admin'), ('PRODUCT_MANAGER', 'Product Manager'), ('ORDER_MANAGER', 'Order Manager'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('CUSTOMER_SUPPORT', 'Customer Support'), ('FINANCE_ACCOUNTING', 'Finance & Accounting'), ('SHOP_STAFF_LIMITED', 'Limited Staff')], db_index=True, default='SHOP_STAFF_LIMITED', max_length=30)),
                ('custom_permissions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'tenant'], name='authenticat_user_id_4adb6c_idx'), models.Index(fields=['tenant', 'role'], name='authenticat_tenant__f4d3df_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
