apiVersion: v1
kind: Service
metadata:
  name: identity-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: identity-db
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: catalog-db
---
apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: order-db
---
apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: payment-db
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: inventory-db
---
apiVersion: v1
kind: Service
metadata:
  name: finance-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: finance-db
---
apiVersion: v1
kind: Service
metadata:
  name: cart-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: cart-db
---
apiVersion: v1
kind: Service
metadata:
  name: media-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: media-db
---
apiVersion: v1
kind: Service
metadata:
  name: chat-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: chat-db
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: recommendation-db
---
apiVersion: v1
kind: Service
metadata:
  name: notification-db
  namespace: microservices
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: notification-db
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: microservices
spec:
  ports:
    - port: 7474
      targetPort: 7474
      name: http
    - port: 7687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
