apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: microservices
spec:
  ports:
    - port: 2181
      targetPort: 2181
      name: client
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: microservices
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: microservices
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
