apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50053
      targetPort: 50053
      name: grpc
  selector:
    app: identity-service
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: catalog-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50054
      targetPort: 50054
      name: grpc
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50055
      targetPort: 50055
      name: grpc
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50052
      targetPort: 50052
      name: grpc
  selector:
    app: inventory-service
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50056
      targetPort: 50056
      name: grpc
  selector:
    app: finance-service
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50057
      targetPort: 50057
      name: grpc
  selector:
    app: cart-service
---
apiVersion: v1
kind: Service
metadata:
  name: media-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 50058
      targetPort: 50058
      name: grpc
  selector:
    app: media-service
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: chat-service
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: recommendation-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: notification-service
