apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  namespace: microservices
spec:
  serviceName: neo4j
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      enableServiceLinks: false
      containers:
        - name: neo4j
          image: neo4j:5.20.0-community
          imagePullPolicy: IfNotPresent
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NEO4J_AUTH
          ports:
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["cypher-shell", "-u", "neo4j", "-p", "recommendation_pass", "RETURN 1"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: ["cypher-shell", "-u", "neo4j", "-p", "recommendation_pass", "RETURN 1"]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: neo4j-pvc
