# Generated by Django 4.2.30 on 2026-09-13 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ORDER', 'Order Update'), ('PAYMENT', 'Payment Status'), ('SYSTEM', 'System Alert'), ('PROMO', 'Promotion'), ('SHIPMENT', 'Shipment Status'), ('ITEM_REQUEST', 'Product Request'), ('CHAT', 'Chat Message'), ('CART', 'Cart Event'), ('INVENTORY', 'Inventory Alert'), ('SECURITY', 'Security Alert')], default='SYSTEM', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['tenant_id', 'created_at'], name='notificatio_tenant__b302ab_idx')],
            },
        ),
    ]
