# Generated by Django 4.2.30 on 2026-09-11 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('order_id', models.UUIDField(db_index=True)),
                ('customer_id', models.UUIDField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(default='POLAR', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid / Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20)),
                ('polar_checkout_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('polar_checkout_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='payments_pa_tenant__3ffcb1_idx'), models.Index(fields=['order_id', 'status'], name='payments_pa_order_i_a76289_idx'), models.Index(fields=['customer_id', 'status'], name='payments_pa_custome_25a299_idx'), models.Index(fields=['polar_checkout_id'], name='payments_pa_polar_c_28af33_idx')],
            },
        ),
    ]
