# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import identity_pb2 as identity__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LookupUsers = channel.unary_unary(
                '/identity.IdentityService/LookupUsers',
                request_serializer=identity__pb2.UserLookupRequest.SerializeToString,
                response_deserializer=identity__pb2.UserLookupResponse.FromString,
                _registered_method=True)
        self.CreateInternalNotification = channel.unary_unary(
                '/identity.IdentityService/CreateInternalNotification',
                request_serializer=identity__pb2.NotificationRequest.SerializeToString,
                response_deserializer=identity__pb2.NotificationResponse.FromString,
                _registered_method=True)
        self.CreateAuditLog = channel.unary_unary(
                '/identity.IdentityService/CreateAuditLog',
                request_serializer=identity__pb2.AuditLogRequest.SerializeToString,
                response_deserializer=identity__pb2.AuditLogResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def LookupUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInternalNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAuditLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LookupUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupUsers,
                    request_deserializer=identity__pb2.UserLookupRequest.FromString,
                    response_serializer=identity__pb2.UserLookupResponse.SerializeToString,
            ),
            'CreateInternalNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInternalNotification,
                    request_deserializer=identity__pb2.NotificationRequest.FromString,
                    response_serializer=identity__pb2.NotificationResponse.SerializeToString,
            ),
            'CreateAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuditLog,
                    request_deserializer=identity__pb2.AuditLogRequest.FromString,
                    response_serializer=identity__pb2.AuditLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identity.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identity.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LookupUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/LookupUsers',
            identity__pb2.UserLookupRequest.SerializeToString,
            identity__pb2.UserLookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInternalNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/CreateInternalNotification',
            identity__pb2.NotificationRequest.SerializeToString,
            identity__pb2.NotificationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.IdentityService/CreateAuditLog',
            identity__pb2.AuditLogRequest.SerializeToString,
            identity__pb2.AuditLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
