# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"C\n\x11StockCheckRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1a\n\x12requested_quantity\x18\x02 \x01(\x05\"l\n\x12StockCheckResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cis_available\x18\x02 \x01(\x08\x12\x15\n\rcurrent_stock\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t\"\'\n\x13ReleaseStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"8\n\x14ReleaseStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x12\x43ommitStockRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"7\n\x13\x43ommitStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"K\n\x16InitProductItemRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\";\n\x17InitProductItemResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd6\x02\n\x10InventoryService\x12I\n\nCheckStock\x12\x1c.inventory.StockCheckRequest\x1a\x1d.inventory.StockCheckResponse\x12O\n\x0cReleaseStock\x12\x1e.inventory.ReleaseStockRequest\x1a\x1f.inventory.ReleaseStockResponse\x12L\n\x0b\x43ommitStock\x12\x1d.inventory.CommitStockRequest\x1a\x1e.inventory.CommitStockResponse\x12X\n\x0fInitProductItem\x12!.inventory.InitProductItemRequest\x1a\".inventory.InitProductItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKCHECKREQUEST']._serialized_start=30
  _globals['_STOCKCHECKREQUEST']._serialized_end=97
  _globals['_STOCKCHECKRESPONSE']._serialized_start=99
  _globals['_STOCKCHECKRESPONSE']._serialized_end=207
  _globals['_RELEASESTOCKREQUEST']._serialized_start=209
  _globals['_RELEASESTOCKREQUEST']._serialized_end=248
  _globals['_RELEASESTOCKRESPONSE']._serialized_start=250
  _globals['_RELEASESTOCKRESPONSE']._serialized_end=306
  _globals['_COMMITSTOCKREQUEST']._serialized_start=308
  _globals['_COMMITSTOCKREQUEST']._serialized_end=346
  _globals['_COMMITSTOCKRESPONSE']._serialized_start=348
  _globals['_COMMITSTOCKRESPONSE']._serialized_end=403
  _globals['_INITPRODUCTITEMREQUEST']._serialized_start=405
  _globals['_INITPRODUCTITEMREQUEST']._serialized_end=480
  _globals['_INITPRODUCTITEMRESPONSE']._serialized_start=482
  _globals['_INITPRODUCTITEMRESPONSE']._serialized_end=541
  _globals['_INVENTORYSERVICE']._serialized_start=544
  _globals['_INVENTORYSERVICE']._serialized_end=886
# @@protoc_insertion_point(module_scope)
