# Generated by Django 4.2.30 on 2026-09-11 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'code'], name='inventory_w_tenant__36f20d_idx')],
                'unique_together': {('tenant_id', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('quantity_available', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Inbound Restock'), ('OUTBOUND', 'Outbound Fulfillment'), ('RESERVED', 'Reserved for Order'), ('RELEASED', 'Released Reservation')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'indexes': [models.Index(fields=['inventory_item', '-created_at'], name='inventory_s_invento_208301_idx'), models.Index(fields=['tenant_id', 'reference_id'], name='inventory_s_tenant__0cac20_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant_id', 'product_id'], name='inventory_i_tenant__d980d7_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant_id', 'warehouse'], name='inventory_i_tenant__00a8e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('tenant_id', 'product_id', 'warehouse')},
        ),
    ]
