# Generated by Django 4.2.30 on 2026-09-11 05:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_products', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='PriceDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('JPY', 'JPY - Japanese Yen'), ('CAD', 'CAD - Canadian Dollar'), ('AUD', 'AUD - Australian Dollar'), ('AED', 'AED - UAE Dirham'), ('SAR', 'SAR - Saudi Riyal'), ('ETB', 'ETB - Ethiopian Birr'), ('KES', 'KES - Kenyan Shilling'), ('INR', 'INR - Indian Rupee')], default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_detail', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'currency'], name='catalog_pro_tenant__330e5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.product')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'product'], name='catalog_pro_user_id_66fe0d_idx')],
                'unique_together': {('user_id', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'category'], name='catalog_pro_tenant__48a14c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'subcategory'], name='catalog_pro_tenant__cf59a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', 'sku'], name='catalog_pro_tenant__0d67ea_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant_id', '-created_at'], name='catalog_pro_tenant__94c803_idx'),
        ),
        migrations.AddIndex(
            model_name='pricediscount',
            index=models.Index(fields=['tenant_id', 'is_active', 'start_time', 'end_time'], name='catalog_pri_tenant__91d532_idx'),
        ),
        migrations.AddIndex(
            model_name='pricediscount',
            index=models.Index(fields=['product', 'is_active'], name='catalog_pri_product_6d502e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricediscount',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pri_categor_e54b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant_id', 'parent'], name='catalog_cat_tenant__e30d07_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant_id', 'slug'], name='catalog_cat_tenant__b167b5_idx'),
        ),
    ]
