# Generated by Django 4.2.30 on 2026-09-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='variant_attributes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
