# Generated by Django 4.2.30 on 2026-09-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_variant_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='category',
            field=models.CharField(blank=True, default='COLOR', max_length=50),
        ),
    ]
