# Generated by Django 4.2.30 on 2026-09-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='polar_product_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
