# Generated by Django 4.2.30 on 2026-09-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_couponredemption'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='catalog_cou_order_i_755d10_idx',
            old_name='coupon_redemption_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='catalog_cou_custome_b58cc5_idx',
            old_name='coupon_redemption_customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='couponredemption',
            new_name='catalog_cou_discoun_816582_idx',
            old_name='coupon_redemption_code_status_idx',
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='times_used',
            field=models.PositiveIntegerField(default=0, help_text='Current confirmed redemption count. Modified only inside select_for_update transactions.'),
        ),
        migrations.AlterField(
            model_name='discountcode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum total redemptions across all customers. NULL = unlimited.', null=True),
        ),
    ]
