# Generated by Django 4.2.30 on 2026-09-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_rename_coupon_redemption_order_status_idx_catalog_cou_order_i_755d10_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='user_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
