# Generated by Django 4.2.30 on 2026-09-11 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('account_code', models.CharField(db_index=True, max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('normal_balance', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='ISSUED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entry_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='POSTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], db_index=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_lines', to='finance.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant_id', '-created_at'], name='finance_jou_tenant__38b288_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant_id', 'reference_id'], name='finance_jou_tenant__7d8fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant_id', 'status'], name='finance_inv_tenant__e82747_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant_id', 'account_code'], name='finance_acc_tenant__de270c_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant_id', 'account_type'], name='finance_acc_tenant__9e64ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant_id', 'account_code')},
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry', 'account'], name='finance_jou_journal_5dd73f_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account', 'entry_type'], name='finance_jou_account_88b1c5_idx'),
        ),
    ]
