# Generated by Django 4.2.30 on 2026-09-11 21:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_customer_id_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('platform_fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available_payout_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id'], name='finance_ten_tenant__77608f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('entry_type', models.CharField(choices=[('CREDIT_SALE', 'Gross Sale Revenue Credit'), ('DEBIT_PLATFORM_FEE', 'SaaS Platform Fee Debit'), ('DEBIT_PAYOUT', 'Shop Payout Debit'), ('CREDIT_REFUND', 'Order Refund Adjustment')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.tenantledger')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', '-created_at'], name='finance_led_tenant__67b88e_idx'), models.Index(fields=['ledger', '-created_at'], name='finance_led_ledger__0fb2fc_idx')],
            },
        ),
    ]
