# Generated by Django 4.2.30 on 2026-09-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financialriskevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialriskevent',
            new_name='finance_fin_severit_94ff78_idx',
            old_name='risk_evt_severity_resolved_idx',
        ),
        migrations.RenameIndex(
            model_name='financialriskevent',
            new_name='finance_fin_tenant__bbe1ad_idx',
            old_name='risk_evt_tenant_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='financialriskevent',
            new_name='finance_fin_order_i_656dc2_idx',
            old_name='risk_evt_order_idx',
        ),
    ]
