# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    import catalog_pb2 as catalog__pb2
except ImportError:
    from . import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/catalog.ProductService/GetProduct',
                request_serializer=catalog__pb2.ProductRequest.SerializeToString,
                response_deserializer=catalog__pb2.ProductResponse.FromString,
                _registered_method=True)
        self.ValidateCoupon = channel.unary_unary(
                '/catalog.ProductService/ValidateCoupon',
                request_serializer=catalog__pb2.CouponValidateRequest.SerializeToString,
                response_deserializer=catalog__pb2.CouponValidateResponse.FromString,
                _registered_method=True)
        self.RedeemCoupon = channel.unary_unary(
                '/catalog.ProductService/RedeemCoupon',
                request_serializer=catalog__pb2.CouponRedeemRequest.SerializeToString,
                response_deserializer=catalog__pb2.CouponRedeemResponse.FromString,
                _registered_method=True)
        self.ConfirmCoupon = channel.unary_unary(
                '/catalog.ProductService/ConfirmCoupon',
                request_serializer=catalog__pb2.CouponConfirmRequest.SerializeToString,
                response_deserializer=catalog__pb2.CouponConfirmResponse.FromString,
                _registered_method=True)
        self.ReverseCoupon = channel.unary_unary(
                '/catalog.ProductService/ReverseCoupon',
                request_serializer=catalog__pb2.CouponReverseRequest.SerializeToString,
                response_deserializer=catalog__pb2.CouponReverseResponse.FromString,
                _registered_method=True)
        self.GetProductPolarId = channel.unary_unary(
                '/catalog.ProductService/GetProductPolarId',
                request_serializer=catalog__pb2.PolarIdRequest.SerializeToString,
                response_deserializer=catalog__pb2.PolarIdResponse.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/catalog.ProductService/ListProducts',
                request_serializer=catalog__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=catalog__pb2.ListProductsResponse.FromString,
                _registered_method=True)


class ProductServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedeemCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseCoupon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductPolarId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=catalog__pb2.ProductRequest.FromString,
                    response_serializer=catalog__pb2.ProductResponse.SerializeToString,
            ),
            'ValidateCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateCoupon,
                    request_deserializer=catalog__pb2.CouponValidateRequest.FromString,
                    response_serializer=catalog__pb2.CouponValidateResponse.SerializeToString,
            ),
            'RedeemCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.RedeemCoupon,
                    request_deserializer=catalog__pb2.CouponRedeemRequest.FromString,
                    response_serializer=catalog__pb2.CouponRedeemResponse.SerializeToString,
            ),
            'ConfirmCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmCoupon,
                    request_deserializer=catalog__pb2.CouponConfirmRequest.FromString,
                    response_serializer=catalog__pb2.CouponConfirmResponse.SerializeToString,
            ),
            'ReverseCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseCoupon,
                    request_deserializer=catalog__pb2.CouponReverseRequest.FromString,
                    response_serializer=catalog__pb2.CouponReverseResponse.SerializeToString,
            ),
            'GetProductPolarId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductPolarId,
                    request_deserializer=catalog__pb2.PolarIdRequest.FromString,
                    response_serializer=catalog__pb2.PolarIdResponse.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=catalog__pb2.ListProductsRequest.FromString,
                    response_serializer=catalog__pb2.ListProductsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'catalog.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('catalog.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/GetProduct',
            catalog__pb2.ProductRequest.SerializeToString,
            catalog__pb2.ProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/ValidateCoupon',
            catalog__pb2.CouponValidateRequest.SerializeToString,
            catalog__pb2.CouponValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedeemCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/RedeemCoupon',
            catalog__pb2.CouponRedeemRequest.SerializeToString,
            catalog__pb2.CouponRedeemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/ConfirmCoupon',
            catalog__pb2.CouponConfirmRequest.SerializeToString,
            catalog__pb2.CouponConfirmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReverseCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/ReverseCoupon',
            catalog__pb2.CouponReverseRequest.SerializeToString,
            catalog__pb2.CouponReverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductPolarId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/GetProductPolarId',
            catalog__pb2.PolarIdRequest.SerializeToString,
            catalog__pb2.PolarIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/catalog.ProductService/ListProducts',
            catalog__pb2.ListProductsRequest.SerializeToString,
            catalog__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
