# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import catalog_pb2 as catalog__pb2

class ProductServiceStub(object):
  """Service definition for Catalog Product Service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProduct = channel.unary_unary(
        '/catalog.ProductService/GetProduct',
        request_serializer=catalog__pb2.ProductRequest.SerializeToString,
        response_deserializer=catalog__pb2.ProductResponse.FromString,
        )

class ProductServiceServicer(object):
  """Service definition for Catalog Product Service
  """

  def GetProduct(self, request, context):
    """Synchronous gRPC call to retrieve product stock and price
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

def add_ProductServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProduct': grpc.unary_unary_rpc_method_handler(
          servicer.GetProduct,
          request_deserializer=catalog__pb2.ProductRequest.FromString,
          response_serializer=catalog__pb2.ProductResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_rpc_handler(
      'catalog.ProductService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
