# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x07\x63\x61talog\"\x1c\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"v\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x13\n\x0bstock_count\x18\x04 \x01(\x05\x12\r\n\x05\x66ound\x18\x05 \x01(\x08\x12\x15\n\rerror_message\x18\x06 \x01(\t2Q\n\x0eProductService\x12?\n\nGetProduct\x12\x17.catalog.ProductRequest\x1a\x18.catalog.ProductResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=26
  _globals['_PRODUCTREQUEST']._serialized_end=54
  _globals['_PRODUCTRESPONSE']._serialized_start=56
  _globals['_PRODUCTRESPONSE']._serialized_end=174
  _globals['_PRODUCTSERVICE']._serialized_start=176
  _globals['_PRODUCTSERVICE']._serialized_end=257
# @@protoc_insertion_point(module_scope)
