# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'identity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eidentity.proto\x12\x08identity\"E\n\x11UserLookupRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"m\n\x08UserData\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x12\n\nfirst_name\x18\x05 \x01(\t\x12\x11\n\tlast_name\x18\x06 \x01(\t\"7\n\x12UserLookupResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.identity.UserData\"y\n\x13NotificationRequest\x12\x14\n\x0crecipient_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x19\n\x11notification_type\x18\x05 \x01(\t\"@\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0fnotification_id\x18\x02 \x01(\t\"l\n\x0f\x41uditLogRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x11\n\ttenant_id\x18\x04 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x05 \x01(\t\"#\n\x10\x41uditLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x81\x02\n\x0fIdentityService\x12H\n\x0bLookupUsers\x12\x1b.identity.UserLookupRequest\x1a\x1c.identity.UserLookupResponse\x12[\n\x1a\x43reateInternalNotification\x12\x1d.identity.NotificationRequest\x1a\x1e.identity.NotificationResponse\x12G\n\x0e\x43reateAuditLog\x12\x19.identity.AuditLogRequest\x1a\x1a.identity.AuditLogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERLOOKUPREQUEST']._serialized_start=28
  _globals['_USERLOOKUPREQUEST']._serialized_end=97
  _globals['_USERDATA']._serialized_start=99
  _globals['_USERDATA']._serialized_end=208
  _globals['_USERLOOKUPRESPONSE']._serialized_start=210
  _globals['_USERLOOKUPRESPONSE']._serialized_end=265
  _globals['_NOTIFICATIONREQUEST']._serialized_start=267
  _globals['_NOTIFICATIONREQUEST']._serialized_end=388
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=390
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=454
  _globals['_AUDITLOGREQUEST']._serialized_start=456
  _globals['_AUDITLOGREQUEST']._serialized_end=564
  _globals['_AUDITLOGRESPONSE']._serialized_start=566
  _globals['_AUDITLOGRESPONSE']._serialized_end=601
  _globals['_IDENTITYSERVICE']._serialized_start=604
  _globals['_IDENTITYSERVICE']._serialized_end=861
# @@protoc_insertion_point(module_scope)
