# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import inventory_pb2 as inventory__pb2


class InventoryServiceStub(object):
    """Service definition for Inventory Service"""

    def __init__(self, channel):
        self.CheckStock = channel.unary_unary(
            '/inventory.InventoryService/CheckStock',
            request_serializer=inventory__pb2.StockCheckRequest.SerializeToString,
            response_deserializer=inventory__pb2.StockCheckResponse.FromString,
        )


class InventoryServiceServicer(object):
    """Service definition for Inventory Service"""

    def CheckStock(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CheckStock': grpc.unary_unary_rpc_method_handler(
            servicer.CheckStock,
            request_deserializer=inventory__pb2.StockCheckRequest.FromString,
            response_serializer=inventory__pb2.StockCheckResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'inventory.InventoryService', rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
