# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\"C\n\x11StockCheckRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1a\n\x12requested_quantity\x18\x02 \x01(\x05\"l\n\x12StockCheckResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x14\n\x0cis_available\x18\x02 \x01(\x08\x12\x15\n\rcurrent_stock\x18\x03 \x01(\x05\x12\x15\n\rerror_message\x18\x04 \x01(\t2]\n\x10InventoryService\x12I\n\nCheckStock\x12\x1c.inventory.StockCheckRequest\x1a\x1d.inventory.StockCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKCHECKREQUEST']._serialized_start=30
  _globals['_STOCKCHECKREQUEST']._serialized_end=97
  _globals['_STOCKCHECKRESPONSE']._serialized_start=99
  _globals['_STOCKCHECKRESPONSE']._serialized_end=207
  _globals['_INVENTORYSERVICE']._serialized_start=209
  _globals['_INVENTORYSERVICE']._serialized_end=302
