# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"\x91\x01\n\x0f\x43heckoutRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x12\n\nreturn_url\x18\x04 \x01(\t\x12\x12\n\ncancel_url\x18\x05 \x01(\t\x12\x11\n\ttenant_id\x18\x06 \x01(\t\x12\x0f\n\x07user_id\x18\x07 \x01(\t\"t\n\x10\x43heckoutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x63heckout_url\x18\x02 \x01(\t\x12\x12\n\npayment_id\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t2W\n\x0ePaymentService\x12\x45\n\x0e\x43reateCheckout\x12\x18.payment.CheckoutRequest\x1a\x19.payment.CheckoutResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKOUTREQUEST']._serialized_start=27
  _globals['_CHECKOUTREQUEST']._serialized_end=172
  _globals['_CHECKOUTRESPONSE']._serialized_start=174
  _globals['_CHECKOUTRESPONSE']._serialized_end=290
  _globals['_PAYMENTSERVICE']._serialized_start=292
  _globals['_PAYMENTSERVICE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
