# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\x12\x05media\"#\n\x0fGetMediaRequest\x12\x10\n\x08media_id\x18\x01 \x01(\t\"\x8e\x01\n\x10GetMediaResponse\x12\x10\n\x08media_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x0c\n\x04size\x18\x05 \x01(\x03\x12\r\n\x05\x66ound\x18\x06 \x01(\x08\x12\x15\n\rerror_message\x18\x07 \x01(\t2K\n\x0cMediaService\x12;\n\x08GetMedia\x12\x16.media.GetMediaRequest\x1a\x17.media.GetMediaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETMEDIAREQUEST']._serialized_start=22
  _globals['_GETMEDIAREQUEST']._serialized_end=57
  _globals['_GETMEDIARESPONSE']._serialized_start=60
  _globals['_GETMEDIARESPONSE']._serialized_end=202
  _globals['_MEDIASERVICE']._serialized_start=204
  _globals['_MEDIASERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
