# Generated by Django 4.2.30 on 2026-09-11 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('uploaded_by', models.UUIDField(blank=True, db_index=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('storage_path', models.CharField(max_length=500)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='IMAGE', max_length=20)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('SHARED', 'Shared')], db_index=True, default='PUBLIC', max_length=20)),
                ('shared_with_users', models.JSONField(blank=True, default=list, help_text='List of user UUID strings granted access')),
                ('shared_with_tenants', models.JSONField(blank=True, default=list, help_text='List of tenant UUID strings granted access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='media_media_tenant__397604_idx'), models.Index(fields=['uploaded_by', 'visibility'], name='media_media_uploade_00f235_idx')],
            },
        ),
    ]
