# Generated by Django 4.2.30 on 2026-09-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='shared_with_users',
            field=models.JSONField(blank=True, default=list, help_text='List of user UUID/ID strings granted access'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
