# Generated by Django 4.2.30 on 2026-09-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_variant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
