# Generated by Django 4.2.30 on 2026-09-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
