# Generated by Django 4.2.30 on 2026-09-11 22:33

from django.db import migrations, models
import orders.models.shipping


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_chat_conversation_and_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='orders_conv_tenant__597af9_idx',
            old_name='orders_conv_tenant_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='orders_conv_tenant__2c4e98_idx',
            old_name='orders_conv_tenant_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='statushistory',
            new_name='orders_stat_entity__561da1_idx',
            old_name='orders_stat_entity__idx',
        ),
        migrations.RenameIndex(
            model_name='statushistory',
            new_name='orders_stat_created_6602fb_idx',
            old_name='orders_stat_created_idx',
        ),
        migrations.AlterField(
            model_name='shipping',
            name='tracking_code',
            field=models.CharField(db_index=True, default=orders.models.shipping.Shipping.generate_tracking_code, max_length=100, unique=True),
        ),
    ]
