# Generated by Django 4.2.30 on 2026-09-12 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(db_index=True)),
                ('product_id', models.UUIDField(db_index=True)),
                ('interaction_type', models.CharField(choices=[('VIEW', 'View'), ('LIKE', 'Like'), ('WISHLIST', 'Wishlist'), ('CART', 'Cart'), ('PURCHASE', 'Purchase'), ('REVIEW', 'Review')], db_index=True, max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'interaction_type'], name='recommendat_user_id_ef4939_idx'), models.Index(fields=['tenant_id', 'product_id'], name='recommendat_tenant__b00eae_idx'), models.Index(fields=['tenant_id', 'user_id'], name='recommendat_tenant__bc685a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductMetadataCache',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('category_name', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rating_avg', models.FloatField(default=0.0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_id', 'category_id'], name='recommendat_tenant__5c0c25_idx'), models.Index(fields=['tenant_id', '-purchase_count'], name='recommendat_tenant__9b83de_idx')],
            },
        ),
        migrations.CreateModel(
            name='CachedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recommendation_type', models.CharField(choices=[('PERSONALIZED', 'Personalized'), ('SIMILAR', 'Similar Products'), ('CO_PURCHASE', 'Frequently Bought Together'), ('TRENDING', 'Trending Products')], db_index=True, max_length=30)),
                ('source_product_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('recommendations_json', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'recommendation_type'], name='recommendat_user_id_94fd29_idx'), models.Index(fields=['source_product_id', 'recommendation_type'], name='recommendat_source__6dfb95_idx'), models.Index(fields=['tenant_id', 'recommendation_type'], name='recommendat_tenant__0f53db_idx')],
                'unique_together': {('tenant_id', 'user_id', 'recommendation_type', 'source_product_id')},
            },
        ),
    ]
