# Generated by Django 4.2.30 on 2026-09-11 22:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.UUIDField(db_index=True)),
                ('sender_name', models.CharField(blank=True, default='', max_length=150)),
                ('sender_role', models.CharField(blank=True, default='MEMBER', max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('FILE', 'File Attachment'), ('SYSTEM', 'System Notification')], default='TEXT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(default='Chat Room', max_length=255)),
                ('room_type', models.CharField(choices=[('DIRECT', 'Direct 1-on-1'), ('GROUP', 'Group Chat'), ('ORDER_SUPPORT', 'Order Support')], default='DIRECT', max_length=20)),
                ('order_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_by', models.UUIDField(db_index=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_file_id', models.UUIDField(db_index=True, help_text='Reference ID in media_service')),
                ('uploaded_by', models.UUIDField(db_index=True)),
                ('uploader_name', models.CharField(blank=True, default='', max_length=150)),
                ('filename', models.CharField(max_length=255)),
                ('file_url', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to='chat.chatroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('user_role', models.CharField(blank=True, default='CUSTOMER', max_length=50)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatroom')),
            ],
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['tenant_id', 'room_type'], name='chat_chatro_tenant__963f31_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_by'], name='chat_chatro_created_e7bcea_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.sharedfile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['user_id', 'room'], name='chat_roompa_user_id_a31ff4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomparticipant',
            unique_together={('room', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='chat_chatme_room_id_466ea2_idx'),
        ),
    ]
