# Generated by Django 4.2.30 on 2026-09-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_file_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Direct reference ID to MediaFile in media_service', null=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['media_file_id'], name='chat_chatme_media_f_f9b3fd_idx'),
        ),
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
