# Generated by Django 4.2.30 on 2026-09-11 23:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_sharedfile_room_remove_chatmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=150)),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.chatmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'emoji'], name='chat_reacti_message_ca5ecd_idx')],
                'unique_together': {('message', 'user_id', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='MessageRecipientStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read')], default='SENT', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_statuses', to='chat.chatmessage')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'status'], name='chat_messag_user_id_9cf7e2_idx'), models.Index(fields=['message', 'status'], name='chat_messag_message_c8f6c2_idx')],
                'unique_together': {('message', 'user_id')},
            },
        ),
    ]
