apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gateway-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: admin-portal-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: admin-portal
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storefront-site-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: storefront-site
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: identity-service-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: identity-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-service-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: catalog-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: microservices
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: order-service
