apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  IDENTITY_POSTGRES_PASSWORD: "identity_pass"
  CATALOG_POSTGRES_PASSWORD: "catalog_pass"
  ORDER_POSTGRES_PASSWORD: "order_pass"
  PAYMENT_POSTGRES_PASSWORD: "payment_pass"
  INVENTORY_POSTGRES_PASSWORD: "inventory_pass"
  FINANCE_POSTGRES_PASSWORD: "finance_pass"
  CART_POSTGRES_PASSWORD: "cart_pass"
  MEDIA_POSTGRES_PASSWORD: "media_pass"
  CHAT_POSTGRES_PASSWORD: "chat_pass"
  RECOMMENDATION_POSTGRES_PASSWORD: "recommendation_pass"
  NOTIFICATION_POSTGRES_PASSWORD: "notification_pass"
  NEO4J_PASSWORD: "recommendation_pass"
  NEO4J_AUTH: "neo4j/recommendation_pass"
  POLAR_API_KEY: "polar_oat_TAvxG0LN70S7eUhsTTyplGoIM0y79dZjccUJr0R2HlK"
  POLAR_WEBHOOK_SECRET: "whsec_MtTI8Ae4Q3y8cSdSFL3Ev9Zxu75G7heqR8P93quxy6A="
  DJANGO_SUPERUSER_PASSWORD: "changeme"
